#!/usr/bin/env bash
cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/sdmenu_run"
[ ! -e "$cachedir" ] && mkdir -p "$cachedir"
IFS=:
if stest -dqr -n "$cache" $PATH 2>/dev/null; then
    stest -flx $PATH 2>/dev/null | sort -u | tee "$cache"
else
    cat "$cache"
fi
